package com.zoho.booktickets.constant;

public class Constant {
	
	public static final String ID_COUNT          = "id_count";
    public static final String ADDRESS_ID        = "address_id";
    public static final String STREET            = "street";
    public static final String CITY              = "city";
    public static final String STATE             = "state";
    public static final String PINCODE           = "pincode";
    public static final String LANDMARK          = "landmark";
    public static final String USER_ID           = "user_id";
    public static final String USER_ROLE         = "role";
    public static final String USER_NAME         = "username";
    public static final String MOBILE_NO         = "mob_no";
    public static final String EMAIL_ID          = "email_id";
    public static final String SEX               = "sex";
    public static final String THEATER_ID        = "theater_id";
    public static final String THAT_ADDRESS_ID   = "theater_address_id";
    public static final String THEATER_NAME      = "theater_name";
    public static final String THEATER_SCREENS   = "screens_list";
    public static final String THEATER_MOVIES    = "movies_list";
    public static final String THEATER_RATING    = "rating";
    public static final String MOVIE_ID          = "movie_id";
    public static final String MOVIE_NAME        = "moviename";
    public static final String MOVIE_TYPE        = "movie_type";
    public static final String MOVIE_STATUS      = "movie_status";
    public static final String BOOKING_ID        = "booking_id";
    public static final String BOOK_USER_ID      = "book_user_id";
    public static final String BOOK_THEATER_ID   = "book_theater_id";
    public static final String BOOK_MOVIE_ID     = "book_movie_id";
    public static final String SCREEN_NO         = "screen_no";
    public static final String SCREEN_ID         = "screen_id";
    public static final String SCREEN_SEATS      = "seats";
    public static final String SCREEN_MOVIE_ID   = "screen_movie_id";
    public static final String SHOW_TIMES        = "show_times";
    public static final String BOOKED_SEATS      = "booked_seats";
    public static final String SHOW_DATE_TIME    = "show_date_time";
    public static final String BOOKED_DATE_TIME  = "booked_date_time";
    public static final String GENERATED_ID      = "generated_key";
    public static final String URL               = "db.URL";
    public static final String USERNAME          = "db.USERNAME";
    public static final String PASSWORD          = "db.PASSWORD";
    public static final String DB_DRIVER_CLASS   = "db.DB_DRIVER_CLASS";
    public static final String DATE_FORMATE      = "yyyy-MM-dd";
    public static final String HOST_URL          = "http://localhost:8080/BookMyTicket-1";
    public static final String PORT_URL          = "http://localhost:8070/BookMyTicket-2";
    public static final String DB_FILE           = "C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/BookMyTicket-1/resources/log4j.properties";
    public static final String EMAIL_PDF_SEND    = "C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/BookMyTicket-1/resources/BookTicket.pdf";
    public static final String TOKEN_SECRET_KEY  = "oeRaYY7Wo24sDqKSX3IM9ASGmdGPmkTd9jo1QTy4b7P9Ze5_9hKolVX8xNrQDcNRfVEdTZNOuOyqEGhXEbdJI-ZQ19k_o9MI0y3eZN2lp9jow55FfXMiINEdt1XR85VipRLSOkT6kSpzs2x-jbLDiz9iFVzkd81YKxMgPA7VfZeQUm4n-mOmnWMaVX30zGFU4L3oPBctYKkl4dYfqYWqRNfrgPJVi5DGFjywgxx0ASEiJHtV72paI3fDR2XwlSkyhhmY-ICjCRmsJN4fX1pdoL8a18-aQrvyu4j0Os6dVPYIoPvvY0SAZtWYKHfM15g7A3HD4cVREf9cUsprCRK93w";
    public static final String DB_CREATE_XML     = "C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/BookMyTicket-1/resources/createtable.xml";
    public static final String I_KEY             = "DIHKUAYJW4HBS348PG77";
    public static final String S_KEY             = "x8DoPVU62ymMyjqwGMzW0vz7WIwmLQyMEXU2SCJX";
    public static final String A_KEY             = "d3ur0239rjf093240f2j9jewij0q832d3u0jd02j0823u0dj438jf0ih028hj2h82h8";
}